### ISSUE TITLE
Generating coverage report fails with "Cannot assign to read only property 'column' of object '#<Object>'"

### ISSUE THREAD

**Issue by rosczja** [istanbuljs/v8-to-istanbul#193] opened 2022-05-12 08:24 UTC
I upgraded an internal codebase to Jest 28 which uses the latest version of v8-to-istanbul package and the generation of a coverage report suddenly fails with:

```
TypeError: Cannot assign to read only property 'column' of object '#<Object>'
    at CovSource.offsetToOriginalRelative (C:\hlag\Data\git\commons-ui-frontend\node_modules\v8-to-istanbul\lib\source.js:110:18)
    at V8ToIstanbul._maybeRemapStartColEndCol (C:\hlag\Data\git\commons-ui-frontend\node_modules\v8-to-istanbul\lib\v8-to-istanbul.js:215:92)
    at C:\hlag\Data\git\commons-ui-frontend\node_modules\v8-to-istanbul\lib\v8-to-istanbul.js:126:60
    at Array.forEach (<anonymous>)
    at C:\hlag\Data\git\commons-ui-frontend\node_modules\v8-to-istanbul\lib\v8-to-istanbul.js:125:20
    at Array.forEach (<anonymous>)
    at V8ToIstanbul.applyCoverage (C:\hlag\Data\git\commons-ui-frontend\node_modules\v8-to-istanbul\lib\v8-to-istanbul.js:124:12)
    at C:\hlag\Data\git\commons-ui-frontend\node_modules\@jest\reporters\build\CoverageReporter.js:628:21
```

I tracked this down to this code line:

https://github.com/istanbuljs/v8-to-istanbul/blob/d0eb7540b53b95c94a3d495e6654d97da03bc068/lib/source.js#L110

For whatever reason `end.column` is `null`.

Can a safeguard be added to this line?

**Comment by SimenB** [comment] 2022-05-12 10:03
Duplicate of #192, just update `@jridgewell/trace-mapping` in your lockfile

**Closed by SimenB** 2022-05-12 10:03 UTC
